version: '3'

services:
  go-serve:
    build:
      context: ./project
    restart: always
    ports:
      - "${GO_PORT}:8080"
    volumes:
      - "./project/log:/log"
    tty: true
### MySQL Container #########################################

  mysql:
    image: mysql:5.7
    volumes:
        - ../data/mysql:/var/lib/mysql
        #- mysql_data:/var/lib/mysql
    expose:
      - 3306
    ports:
      - "${MYSQL_PORT}:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=123456
      - MYSQL_DATABASE=go_test
    restart: always

### PHPMyAdmin Container #########################################

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - "${PHPMYADMIN_PORT}:80"
    links:
        - mysql:db
    depends_on:
      - mysql
    restart: always

### Redis Container #########################################

  redis:
    image: redis:3.2.11
    expose:
      - "6379"
    ports:
      - "${REDIS_PORT}:6379"
    volumes:
      - ../data/redis:/data
    restart: always

### Volumes Setup ###########################################

volumes:
  mysql_data:
networks:
  default:
    external:
      name: ${USER_NETWORK}
